### ISSUE TITLE
Most item icons show blanks on first view

### ISSUE THREAD

**Issue by Midnighit** [bigmanshawn/ConanEvolved_Merchants#10]
When looking into the inventory of a merchant for the first time, most icons usually look like blank white squares. Leaving and reentering the same merchant usually fixes this.

First look at the merchants items: [http://i.imgur.com/DvwRh5H.jpg](url)
Second look at the same merchant: [http://i.imgur.com/30H4Blm.jpg](url)

**Comment by bigmanshawn** [comment]
Yeah ive seen this issue many times, we have to load the assets for the icons since they arnt loaded into memory yet, so first time you do it, you are loading a bunch of icons.   There is no feedback from the loading function that I know of or I would put in a wait for it.  I could add a global delay but it would then make it slow to open even when everything is cached.  

Will look into it with time, may be in next version.

**Comment by Midnighit** [comment]
It's a minor issue compared to the economy breaking ones I reported, so take your time with this one.

**Comment by bigmanshawn** [comment]
This may have been fixed with the upgrade to UE4.15.3 as I was no longer seeing it in the devkit, but would need confirmation from a dedicated server.  I suspect I know the issue but want to be sure before changing the code since it would be some extra overhead.

**Comment by Midnighit** [comment]
Unfortunately I have to confirm that it is still happening even after the
engine upgrade.

Am 14.07.2017 05:53 schrieb "Shawn Sagady" <notifications@github.com>:
